apiVersion: apps/v1
kind: Deployment
metadata:
  name: elysianforest
  namespace: argoelysian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elysianforest
  template:
    metadata:
      labels:
        app: elysianforest
    spec:
      containers:
      - name: server
        image: pwertyman/elysianforest:latest # 방금 푸시한 이미지
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"